steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Set Cloud Run Region
  entrypoint: gcloud
  args: ['config', 'set', 'run/region', '${_REGION}']
- name: 'gcr.io/cloud-builders/docker'
  id: Build the container image
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest',
         '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}',
         '.']
- name: 'gcr.io/cloud-builders/docker'
  id: Push the container image to Cloud Container Registry
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy container image to Cloud Run
  entrypoint: gcloud
  args: ['run', 'deploy', '${_SERVICE_NAME}',
         '--image', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}',
         '--platform', 'managed',
         '--timeout', '600',
         '--service-account', 'otp-sa@one-time-password-via-api.iam.gserviceaccount.com',
         '--tag', '${_TAG}']
substitutions:
  _SERVICE_NAME: one-time-password-via-api
  _TAG: development
  _REGION: us-west1
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}'